version: '3.8'

services:
#  db:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: some_user
#      POSTGRES_PASSWORD: some_password
#      POSTGRES_DB: squeeze-auction
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
#      POSTGRES_HOST: db
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: your_username
#      POSTGRES_PASSWORD: your_password
#      POSTGRES_DB: your_database
      PORT: :4444
      LOG_LEVEL: debug
#    depends_on:
#      - db
    ports:
      - "3333:4444"
#
#volumes:
#  postgres_data:
